
---
# tasks file
- name: Pulling ECR Image From ECR Repository 
  shell: $(aws ecr get-login --no-include-email --region ap-south-1) && docker pull 920156365760.dkr.ecr.ap-south-1.amazonaws.com/gaya3_repo:latest

- name: NGINX Deployment
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        namespace: default
        labels:
          app: nginx
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: "920156365760.dkr.ecr.ap-south-1.amazonaws.com/gaya3_repo:latest"
                imagePullPolicy: Always
                ports:
                  - containerPort: 80
            imagePullSecrets:
              - name: regcred

- name: NGINX Service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: nginx-service
        namespace: default
      spec:
        selector:
          app: nginx
        type: LoadBalancer
        ports:
          - protocol: TCP
            port: 8085
            targetPort: 80
